export const ADDINTEREST_START = 'ADDINTEREST_START';
export const ADDINTEREST_SUCCESS = 'ADDINTEREST_SUCCESS';
export const ADDINTEREST_FAIL = 'ADDINTEREST_FAIL';

export const FETCH_INTERESTS_START = 'FETCH_INTERESTS_START';
export const FETCH_INTERESTS_SUCCESS = 'FETCH_INTERESTS_SUCCESS';
export const FETCH_INTERESTS_FAIL = 'FETCH_INTERESTS_FAIL';
 
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'; 
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'; 
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'; 

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const UNLOCK_CONTACT_USER_START = 'UNLOCK_CONTACT_USER_START';
export const UNLOCK_CONTACT_USER_SUCCESS = 'UNLOCK_CONTACT_USER_SUCCESS';
export const UNLOCK_CONTACT_USER_FAIL = 'UNLOCK_CONTACT_USER_FAIL';